
export const StyleList = [
    { title: "Primary Color", type: 'color', details: '#51ab1a' },
    { title: "Secondary Color", type: 'color', details: '#800080' },
    // { title: "Background Default Color", type: 'color', details: '#303030' },
    // { title: "Background Paper Color", type: 'color', details: '#424242' },
    { title: "Theme", type: 'theme', details: 'dark' },
    { title: "Font Family", type: 'font', details: 'Roboto' },
    { title: "Font Weight Bold", type: 'font', details: 700 },
    { title: "Font Weight Medium", type: 'font', details: 300 },
    { title: "Font Weight Light", type: 'font', details: 500 },
    { title: "Font Weight Regular", type: 'font', details: 400 },
    { title: "Font Size", type: 'font', details: 14 },
    // { title: "h1 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h1 Font Size", type: 'font', details: '6rem' },
    // { title: "h1 Font Weight", type: 'font', details: 300 },
    // { title: "h1 Font Height", type: 'font', details: 1.167 },
    // { title: "h2 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h2 Font Size", type: 'font', details: '3.75rem' },
    // { title: "h2 Font Weight", type: 'font', details: 300 },
    // { title: "h2 Font Height", type: 'font', details: 1.2 },
    // { title: "h3 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h3 Font Size", type: 'font', details: '3rem' },
    // { title: "h3 Font Weight", type: 'font', details: 400 },
    // { title: "h3 Font Height", type: 'font', details: 1.167 },
    // { title: "h4 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h4 Font Size", type: 'font', details: '2.12rem' },
    // { title: "h4 Font Weight", type: 'font', details: 400 },
    // { title: "h4 Font Height", type: 'font', details: 1.235 },
    // { title: "h5 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h5 Font Size", type: 'font', details: '1.334rem' },
    // { title: "h5 Font Weight", type: 'font', details: 400 },
    // { title: "h5 Font Height", type: 'font', details: 1.334 },
    // { title: "h6 Font Family", type: 'font', details: 'Roboto' },
    // { title: "h6 Font Size", type: 'font', details: '1.25rem' },
    // { title: "h6 Font Weight", type: 'font', details: 500 },
    // { title: "h6 Font Height", type: 'font', details: 1.6 },
    // { title: "body1 Font Family", type: 'font', details: 'Roboto' },
    // { title: "body1 Font Size", type: 'font', details: '1rem' },
    // { title: "body1 Font Weight", type: 'font', details: 400 },
    // { title: "body1 Font Height", type: 'font', details: 1.5 },
    // { title: "body2 Font Family", type: 'font', details: 'Roboto' },
    // { title: "body2 Font Size", type: 'font', details: '0.875rem' },
    // { title: "body2 Font Weight", type: 'font', details: 400 },
    // { title: "body2 Font Height", type: 'font', details: 1.43 },
    // { title: "button Font Family", type: 'font', details: 'Roboto' },
    // { title: "button Font Size", type: 'font', details: '0.875rem' },
    // { title: "button Font Weight", type: 'font', details: 500 },
    // { title: "button Font Height", type: 'font', details: 1.75 },
    // { title: "caption Font Family", type: 'font', details: 'Roboto' },
    // { title: "caption Font Size", type: 'font', details: '0.75rem' },
    // { title: "caption Font Weight", type: 'font', details: 400 },
    // { title: "caption Font Height", type: 'font', details: 1.66 },
  ];
  